Implement WⅠP check process at CircleCI (#165)
* chore: 🤖 add check-wip process to circle ci

✅ Closes: #145

* chore: 🤖 delete github actions for wip check

* chore: 🤖 import wip skip process directly

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,6 +19,83 @@ machine_defaults: &machine_defaults
     GO_VERSION: "1.12.5"
 
 jobs:
+  check-skippable-pr:
+    docker:
+      - image: alpine:3.7
+    steps:
+      - run: apk add --no-cache bash curl jq
+      - run:
+          shell: /bin/bash
+          name: Check skippable PR
+          command: |
+            required_env_vars=(
+              "GITHUB_TOKEN"
+              "CIRCLE_PROJECT_USERNAME"
+              "CIRCLE_PROJECT_REPONAME"
+              "CIRCLE_TOKEN"
+              "CIRCLE_BUILD_NUM"
+            )
+            PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | sed -e 's#.*/pull/##')
+
+            for required_env_var in ${required_env_vars[@]}; do
+              if [[ -z "${!required_env_var}" ]]; then
+                printf "${required_env_var} not provided, but that doesn't mean we should skip CI.\n"
+                exit 0
+              fi
+            done
+
+            # Since we're piggybacking off of an existing OAuth var, tweak the var for our uses
+            token=$(printf "${GITHUB_TOKEN}" | cut -d':' -f1)
+
+            headers="Authorization: token $token"
+            api_endpoint="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${PR_NUMBER}"
+
+            # Fetch PR metadata from Github's API and parse fields from json
+            github_res=$(curl --silent --header "${headers}" "${api_endpoint}" | jq '{mergeable_state: .mergeable_state, title: .title}')
+            mergeable_state=$(printf "${github_res}" | jq '.mergeable_state')
+            title=$(printf "${github_res}" | jq '.title' | tr '[:upper:]' '[:lower:]')
+            echo "${title}"
+
+            if [[ "${title}" == "null" && "${mergeable_state}" == "null" ]]; then
+              printf "Couldn't fetch info on PR, but that doesn't mean we should skip CI.\n"
+              exit 0
+            fi
+
+            cancel_running_jobs=0
+
+            if [[ "${mergeable_state}" == "\"draft\"" ]]; then
+              printf "PR is a draft, skipping CI!\n"
+              cancel_running_jobs=1
+            fi
+
+            for skip_token in '[skip ci]' '[ci skip]' '[wip]' 'WIP' 'wip' '🚧'; do
+              if [[ ${title} == *"${skip_token}"* ]]; then
+                printf "Found \"${skip_token}\" in PR title, skipping CI!\n"
+                cancel_running_jobs=1
+              fi
+            done
+
+            if [[ "${cancel_running_jobs}" == 1 ]]; then
+              printf "Attempting to cancel any running jobs"
+              CIRCLE_API_BASE_URL="https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
+              AUTH_PARAMS="circle-token=${CIRCLE_TOKEN}"
+              SELF_BUILD_NUM="${CIRCLE_BUILD_NUM}"
+
+              all_jobs=$(curl --silent --show-error "${CIRCLE_API_BASE_URL}/tree/${CIRCLE_BRANCH}?${AUTH_PARAMS}")
+
+              running_jobs=$(echo "${all_jobs}" | jq "map(if .status == \"running\" or .status == \"not_running\"  then .build_num else \"None\" end) - [${SELF_BUILD_NUM}] - [\"None\"] | .[]")
+
+              for buildNum in $running_jobs; do
+                printf "Canceling ${buildNum}"
+                curl --silent --show-error --request POST "${CIRCLE_API_BASE_URL}/${buildNum}/cancel?${AUTH_PARAMS}" > /dev/null
+              done
+              exit 1
+            else
+              printf "No reason to skip CI, let's go!"
+            fi
+
+            exit 0
+
   fmt:
     <<: *linux_defaults
     steps:
@@ -249,7 +326,10 @@ workflows:
   version: 2.1
   build_and_test:
     jobs:
-      - fmt
+      - check-skippable-pr
+      - fmt:
+          requires:
+            - check-skippable-pr
       - setup_dependencies:
           requires:
             - fmt
